services:
  tax:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - postgres
#    environment:
#      DATABASE_URL: postgres://postgres:postgres@postgres:5432/ktaxes
    volumes:
      - .:/go/src/ktaxes
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
