services:
  tax:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:8080'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - .:/go/src/ktaxes
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    ports:
      - '5432:5432'
  
  
#  postgres://postgres:postgres@postgres:5432/ktaxes
#  
#  export PORT=8080
#  export DATABASE_URL=postgres://postgres:postgres@postgres:5432/ktaxes
#  export ADMIN_USERNAME=adminTax
#  export ADMIN_PASSWORD=admin!